version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: calendarly-backend
    ports:
      - "3000:3000"
    volumes:
      - db-data:/data
      - ./server/backups:/usr/src/app/backups
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: calendarly-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - .env
    restart: unless-stopped

volumes:
  db-data:
    driver: local
